### PR TITLE
test: Test that spikes have expected x-coordinate

### PR DESCRIPTION
**Pull request by marusak**

### CODE REVIEW

**Comment by marusak** [comment]
Now I would like to record a few simple archives and do some wrapper that would load archive, change time, wait for stuff to appear (well, it will have to reload the page) and then call this `getMaximumSpike` wrapped in some other method like `assertSpike`.

**Comment by marusak** [comment]
Added test with preorder archive. I think it has potential. I'll wait for @martinpitt to see what he thinks.
Then it is just a bit of busywork to record archive and check for spikes.

**Review by martinpitt — APPROVED** [review]
I really like this, thanks! I tickled the tests and they are running now.

**Comment by marusak** [comment]
Ok, we should make some plan what else we want to test (like cpu, but see https://github.com/martinpitt/performance-graphs/issues/6) and if there are some specific requirements we have (like big spike followed by smaller spike or stuff like those).

**Pull request merged**
