### PR TITLE
Show current system load averages

### PR DESCRIPTION
**Pull request by martinpitt**
Poll /proc/loadavg for this, as there is currently no internal metrics
channel for this. See this PR for details:
https://github.com/cockpit-project/cockpit/pull/14510

### CODE REVIEW

**Comment by martinpitt** [comment]
Sticking fairly close to the [design](https://garrett.github.io/cockpit-mockweb/metrics/current/):

image

Note I'm still using a `<table>` here. I'd like to change to ct-form or DescriptionList, but let's do that consistently. See issue #16

**Comment by marusak** [comment]
Design-wise I think we can do better.
Having there three numbers does not give much importation to average users. Also there is waay to much empty space on the card to have it as 3 separate rows. Do you think it would make sense to use that?

**Comment by martinpitt** [comment]
@maruak: Agreed that we need to format this better -- for now I'm trying to get all the functionality working an on the page, so that we have a complete picture of what we need to arrange, and where. See #24 about my woes of using `<table>` vs. `DescriptionList` vs. `ct-form`, and #21 will rearrange stuff. Eventually I think we'll have the CPU card show "CPU usage / load / top5" and the memory card "memory usage / swap  usage / top 5", so that we can balance out the number of rows and their layout.

As for presenting this, we could so something like

> **Load:** 1min: 1.23, 5min: 4.12, 15min: 3.23

or

> **Load:** 1min: 1.23 | 5min: 4.12 | 15min: 3.23

(imagine a table-like thing here)

**Comment by martinpitt** [comment]
I added the "1min: ..." thing now, just so that we don't forget about it when we do the final design update.

**Review by marusak — APPROVED** [review]
Thanks!

**Pull request merged**
