### PR TITLE
Several bug fixes

### PR DESCRIPTION
**Pull request by martinpitt**

### CODE REVIEW

**Comment by marusak** [comment]
Could we get test for the last commit? (`Fix scaling of CPU usage graph`)? Ideally prerecording archive on machine with a few cores and then making sure it never exceeds 1.

**Comment by martinpitt** [comment]
@marusak: We'd need to provision a machine with 2 CPUs for that test case. We could use the same /dev/urandom approach as in `testCurrentMetrics`, but I'd like to keep that @nondestructive. So indeed, we either copy that approach or use a pre-recorded archive.

**Comment by martinpitt** [comment]
@marusak : I added a test with a 2-core VM and recording.

**Comment by martinpitt** [comment]
@marusak : oh, that broke an unrelated test -- did you record that on a multi-cpu machine?

**Comment by marusak** [comment]
> did you record that on a multi-cpu machine?

I recorded all archives on VM that was sitting after `./test/check-application`

**Comment by martinpitt** [comment]
@marusak : That test case is actually broken in master -- must have been parallel PR landing :sob: That graph clearly shows a higher load, I get a load of 32.6 there and no higher one (which would define a higher correspondence for what "100%" means). Can you please have a quick look?

**Comment by martinpitt** [comment]
Fixed in PR #15

**Review by marusak — APPROVED** [review]
Thanks for the fixes!

**Pull request merged**
