### PR TITLE
Fix broken history graphs

### LINKED ISSUE #5: New data are "too spiky"
When I leave the page opened for some time:
Screenshot from 2020-08-10 14-49-31

When I reload it then:
Screenshot from 2020-08-10 14-50-41

It seems like every new data is recognized as spike?

### PR DESCRIPTION
**Pull request by martinpitt**
Fixes #5

### CODE REVIEW

**Comment by martinpitt** [comment]
@marusak: Letting a busy VM sit for a while now produces correct graphs for me. Do you mind testing this in your env, and having a look?

**Comment by marusak** [comment]
It looks indeed better. There is still small difference between when data are loaded dynamically vs when they are fetched on page load:
When page was opened for a bit:
withopened

AFter reload:
reloaded

If you look closer at graphs, especially cpu it is visible that it is not the same.

**Comment by martinpitt** [comment]
@marusak: Can you please point out the difference? The "current minute has more data" part is obvious and natural, as you reloaded -- and the graph only auto-refreshes once per minute. Apart from that I can't spot a difference?

**Comment by martinpitt** [comment]
@marusak: As per IRC, these are some "null holes" that the data seems to randomly get, see [my debugging from this morning](https://github.com/martinpitt/performance-graphs/issues/5#issuecomment-688069276). This is unrelated to trying to draw null/false data points, which is what causes most of these woes. So I believe this PR does not cause regressions.

**Review by marusak — APPROVED** [review]
> So I believe this PR does not cause regressions.

Agree with this statement.

**Pull request merged**
