### PR TITLE
Rename page to "metrics"

### PR DESCRIPTION
**Pull request by martinpitt**
This fits better with the other page names, and avoids confusion with
the already existing "performance" manifest, which is tuned (and
probably also ought to be renamed..)

### CODE REVIEW

**Comment by martinpitt** [comment]
@garrett , @andreasn: This is mostly name bikeshedding, but I think "metrics" fits much better into the existing name structure:

```
❱❱❱ cockpit-bridge --packages
apps                 Applications                             /var/home/martin/.local/share/cockpit/apps
base1                                                         /var/home/martin/.local/share/cockpit/base1
dashboard                                                     /var/home/martin/.local/share/cockpit/dashboard
kdump                Kernel Dump                              /var/home/martin/.local/share/cockpit/kdump
machines             Virtual Machines                         /var/home/martin/.local/share/cockpit/machines
metrics              Performance Graphs                       /var/home/martin/.local/share/cockpit/metrics
network              Networking                               /var/home/martin/.local/share/cockpit/networkmanager
pcp                                                           /var/home/martin/.local/share/cockpit/pcp
performance                                                   /var/home/martin/.local/share/cockpit/tuned
playground           Development                              /var/home/martin/.local/share/cockpit/playground
selinux              SELinux                                  /var/home/martin/.local/share/cockpit/selinux
shell                                                         /var/home/martin/.local/share/cockpit/shell
sosreport            Diagnostic Reports                       /var/home/martin/.local/share/cockpit/sosreport
ssh                                                           /var/home/martin/.local/share/cockpit/ssh
starter-kit          Starter Kit                              /var/home/martin/.local/share/cockpit/starter-kit
storage              Storage                                  /var/home/martin/.local/share/cockpit/storaged
system               Overview, Logs, Services, Terminal       /var/home/martin/.local/share/cockpit/systemd
updates              Software Updates                         /var/home/martin/.local/share/cockpit/ostree
users                Accounts                                 /var/home/martin/.local/share/cockpit/users
```

Ignore the "Performance Graphs" label, this will go away once we introduce it into Cockpit.

**Comment by garrett** [comment]
"Performance" by itself could also imply tuning, so "metrics" works. And "graphs" is misleading, as the current stuff is half not-graphs.

Since we're talking about naming: On the Overview page, "View graphs" should probably become something like "View detailed metrics" or "View performance metrics".

**Comment by martinpitt** [comment]
@garrett: Agreed - Indeed that's what I've [done in my "landing" branch](https://github.com/martinpitt/cockpit/commit/bada76f4886a25bc155eb1b59d55db873b2246ed#diff-69a297e3b3df03561dbe6a02cd3a464fR147) - I renamed it to "View details and history". I'm of course happy to rename that.

**Comment by martinpitt** [comment]
Note that this is primarily about renaming the /performance-graphs → /metrics URL path. But this path is by and large not visible to users otherwise.

**Pull request merged**
