### PR TITLE
Put history graphs into a card

### PR DESCRIPTION
**Pull request by marusak**
Now I will replace 'Events' with time select. Wanted to send this separately so we can tweak the design while I work on the time-changing functionality. Design from https://github.com/martinpitt/performance-graphs/issues/35
@garrett and @martinpitt WDYT?

Before:
beforepg

Now:
newheader

And it is sticky, so after scrolling:
issticky

### CODE REVIEW

**Comment by martinpitt** [comment]
I generally like the design, it improves the contrast. I just think the header should have the same left/right padding as the cards, it otherwise looks a bit off.

**Comment by marusak** [comment]
> I just think the header should have the same left/right padding as the cards, it otherwise looks a bit off.

sure, that is the easier case, it is like that on purpose as I copied the design. @garrett WDYT?

**Comment by garrett** [comment]
> it is like that on purpose as I copied the design

I thought I put headers in the cards too? :thinking: 

jump mockup

It probably makes things a little more complex... but I guess if headings go in minute :00, they'll stretch the graph down and it'd work... similar to the events stretching per minute. We'd just have every :00 stretched (_especially_ if it also happens to have an event). I guess that's fine?

**Comment by marusak** [comment]
> I thought I put headers in the cards too? thinking

Yes you did, but that is unrelated to this PR and as you mentioned a bit more complex. I would leave that as a follow up, I just needed to have place for the select (thus moving the header up and while on that putting graphs into a card).

**Comment by marusak** [comment]
Fixed tests

**Comment by marusak** [comment]
I have another changes that are built on top of this.

**Review by martinpitt — APPROVED** [review]
Thanks! There may still be some design changes here, but let's do them once we have everything together, with the "jump to time" and such.

**Comment by garrett** [comment]
> There may still be some design changes here, but let's do them once we have everything together

:100: agree.

Let's keep getting these features in and iterating on top*. Even the mockups go out of date pretty quickly, such as if there are better ideas when implementing (such as @martinpitt's splitting up of CPU/memory hogs and integrating them in the CPU/memory cards instead of the process list I had in my mockup).

_\* not intended to be a joke on the `top` command, but it works_ :wink:

Yeah, this is a little different from my stance on Cockpit, where I want a PR to land when it's feature complete. It's more "Wild West" here, since it's the early days and we're making something that's at least a little bit different from everyone else's performance tools. :wink:

**Comment by martinpitt** [comment]
@garrett: Agreed about the "wild west" thing -- rule and order will reign once we put this into cockpit.git :police_officer:

**Pull request merged**
